### PR TITLE
Perf updates

### PR DESCRIPTION
**Pull request by ghost1face**
Hey, stumbled on this library  and saw a few areas to optimize, short summary:
1. Use case insensitive dictionary
2. Use HashSet<string> instead of List<string>
3. Remove unnecessary `.ToLower` calls
4. Load rules in order of priority (removes need to reverse some of the dictionaries and iterate backward, tying into 5 below)
5. Use foreach instead of `while` and `ElementAt`
6. Used `static readonly` access modifiers on class level rules since they currently do not change

Take a look at the comparisons below `PluralizeTermsFaster` is with the changes made, `PluralizeTerms` is the original code.

If you want to take a look at the benchmarks and run them yourself you can find them here:
https://github.com/ghost1face/Pluralize.NET/tree/perf .  

Test contents and results are as follows:
https://github.com/ghost1face/Pluralize.NET/blob/perf/Pluralize.NET.Performance/Program.cs

``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.885 (1803/April2018Update/Redstone4)
Intel Core i7 CPU 860 2.80GHz (Nehalem), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3416.0
  DefaultJob : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3416.0


```
|               Method |     Mean |     Error |    StdDev |   Median | Rank |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |---------:|----------:|----------:|---------:|-----:|-------:|------:|------:|----------:|
| PluralizeTermsFaster | 231.5 us |  4.534 us |  5.569 us | 230.8 us |    1 | 0.9766 |     - |     - |   4.82 KB |
|       PluralizeTerms | 370.8 us | 10.770 us | 31.074 us | 357.5 us |    2 | 3.4180 |     - |     - |  14.02 KB |

### CODE REVIEW

**Comment by ghost1face** [comment]
Looks like the build succeeded but coverage tests failed here:

```
Failed to upload to coveralls
At line:3 char:1

```

**Comment by sarathkcm** [comment]
Looks like some nice improvements. Thank you. I will take a look at the pull sometime next week. 
Just one quick comment:

> Used static readonly access modifiers on class level rules since they currently do not change

The rules don't currently change, but I wanted to make it configurable at some point in future, by providing methods to add custom rules. If we make these fields static the the custom rules will become globally configured in the code base, and will cause unexpected issues.

Any thoughts on how that can be avoided?

**Comment by ghost1face** [comment]
Well, I didn't want to overload you with changes, also wasn't sure if this repo was being actively maintained.  But I did end up reverting some of the static access modifiers in another branch based on the changes made in this PR.

The branch below has the above changes but also adds missing features such as:
* IsPlural
* IsSingular
* AddIrregularRule
* AddPluralRule
* AddSingularRule
* AddUncountableRule
* Format  (takes in the word and a numerical value and can return `1 cat`  `2 cats` based on input

It puts Pluralizer behind `IPluralize` interface where users can create their own implementation if needed, that way being flexible.  I also expanded the rule-set and tests to be up to date with the javascript library.  I can close this and open up a PR for the full set of changes if you'd like.

https://github.com/ghost1face/Pluralize.NET/tree/is-plural-is-singular

**Comment by ghost1face** [comment]
Closing as these changes will be addressed in #14

**Pull request closed without merging**
